"""Existing bilingual control explanations and tooltip window behavior."""
from __future__ import annotations
import sys
from ..screen_geometry import physical_cursor_position, place_physical_window
import tkinter as tk
from ..ui_widgets import monitor_workarea

TOOLTIPS = {
    "五档预设": "仅设置最终脚本与实时输出的行程倍率：1–5 档为 0.55 / 0.75 / 1 / 1.15 / 1.30；不改变分析方法、识别参数或骨架处理。",
    "仅调整最终输出幅度": "对录制、导出脚本和实时输出生效；原始分析结果不变，现有输出限位与限速继续有效。",
    "急停回中": "立即停止实时输出，并把当前启用的轴回到中间位置。",
    "全行程": "把 L0 切到更大更快的全行程测试参数。",
    "连接并回中": "连接当前选择的设备，并发送回中命令。",
    "连接中...": "正在连接设备；如果端口异常，窗口也会保持可操作。",
    "开始实时输出前确认": "启动设备前最后确认输出模式和上下限。",
    "L0 Only：只上下": "只输出 L0 上下轴，最适合先测试。",
    "Six Axis：六轴": "同时输出 L0/L1/L2/R0/R1/R2。",
    "确认开始": "按当前选择的模式开始实时输出。",
    "取消": "关闭当前确认窗口，不启动输出。",
    "连接设备": "选择 USB 串口或 BLE，并连接 SR6/OSR6 控制器。",
    "输出": "选择只看日志、USB 串口或 BLE UART 输出。",
    "串口": "USB 或蓝牙串口号，例如 COMx。",
    "刷新": "重新扫描电脑上的串口或声音设备。",
    "波特率": "串口通信速度；OSR 常见为 115200。",
    "自动检测 SR6/OSR6": "从可用串口里猜测最可能的 SR6/OSR6 控制口。",
    "BLE 名称": "按蓝牙设备名称过滤扫描结果。",
    "扫描": "扫描附近 BLE UART 设备。",
    "BLE 地址": "BLE 设备地址，扫描后会自动填入。",
    "写入 UUID": "BLE UART 的写入通道 UUID。",
    "断开": "关闭当前设备连接。",
    "查询设备轴": "向串口发送 D2，查看固件开放了哪些 TCode 轴。",
    "实时输出": "屏幕、视频或声音实时转换成 TCode 输出。",
    "下限": "当前轴允许到达的最小 TCode 值。",
    "上限": "当前轴允许到达的最大 TCode 值。",
    "速度": "每帧最多允许变化多少 TCode 数值，越大动作越快。",
    "居中": "发送回中命令。",
    "中等测试": "发送较小幅度的安全测试动作。",
    "上下全幅测试": "只测试 L0 上下轴的完整范围。",
    "SR6/OSR6 六轴轻测": "逐个轻微测试 L0/L1/L2/R0/R1/R2。",
    "开始实时输出": "开始读取输入来源并控制设备。",
    "恢复所有默认设置": "把所有参数恢复到新安装时的默认值；点击后会先二次确认。",
    "显示预览": "打开 3D 模拟器，显示最终输出指令的运动。画面与骨架在分析预览页；模拟器不是硬件反馈。",
    "取消预览": "关闭预览同步；已打开的浏览器页可直接关掉。",
    "停止": "停止实时输出，保持连接。",
    "安全预设": "更慢、更小幅，适合初次测试。",
    "标准预设": "日常推荐的折中参数。",
    "混合分析灵敏": "使用混合分析，并提高跟手程度。",
    "六轴独立上下限": "分别限制每个轴的物理输出范围。",
    "总行程倍率": "围绕中点缩放所有轴行程，不会越过每轴上下限。",
    "L0 总行程倍率": "只缩放 L0 上下轴行程，不改变 L0 的机械上下限。",
    "六轴总行程倍率": "只缩放 L1/L2/R0/R1/R2 辅助轴行程，不影响 L0。",
    "展开六轴单轴行程倍率": "展开后可以分别缩放 L1/L2/R0/R1/R2；最终幅度 = 六轴总行程倍率 × 单轴倍率。",
    "收起六轴单轴行程倍率": "收起 L1/L2/R0/R1/R2 单轴行程倍率。",
    "L1 行程倍率": "L1 前后轴的单独行程倍率，会再乘以六轴总行程倍率。",
    "L2 行程倍率": "L2 左右轴的单独行程倍率，会再乘以六轴总行程倍率。",
    "R0 行程倍率": "R0 扭转轴的单独行程倍率，会再乘以六轴总行程倍率。",
    "R1 行程倍率": "R1 横滚轴的单独行程倍率，会再乘以六轴总行程倍率。直接 Pose 额外随最终 L0 收拢：底部至 2/3 为 1 倍，顶部为 0.5 倍。",
    "R2 行程倍率": "R2 俯仰轴的单独行程倍率，会再乘以六轴总行程倍率。直接 Pose 额外随最终 L0 收拢：底部至 2/3 为 1 倍，顶部为 0.5 倍。",
    "轴": "当前要查看或调整的 TCode 通道。",
    "测量模式": "用滑块手动遥控单个轴，方便保存安全上下限。",
    "滑动即发送": "打开后拖动测量滑块会立刻发送到设备。",
    "位置": "当前手动发送的 TCode 位置值。",
    "发送当前位置": "把测量滑块的位置发送给当前轴。",
    "保存为下限": "把当前测量位置保存为该轴下限。",
    "当前轴回中": "把当前测量轴发送到 5000。",
    "保存为上限": "把当前测量位置保存为该轴上限。",
    "六轴辅助调节（仅混合分析推荐）": "只推荐用于混合分析（推荐-非舞蹈）的 L1/L2/R0/R1/R2 辅助微调；RTM Pose 不接入这里。",
    "展开测量模式和轴上下限": "展开测量模式和每个轴的安全上下限。",
    "收起测量模式和轴上下限": "收起测量模式和每个轴的安全上下限。",
    "展开六轴辅助调节（仅混合分析）": "展开混合分析用的六轴辅助微调。",
    "收起六轴辅助调节（仅混合分析）": "收起混合分析用的六轴辅助微调。",
    "展开 RTM Pose 模型设置": "展开 RTM Pose 的模型路径、模型下载和来源说明。只有选择 RTM Pose 2D 舞蹈模式时才显示。",
    "收起 RTM Pose 模型设置": "收起 RTM Pose 模型设置，保持主界面更清爽。",
    "总强度": "整体放大或缩小非 L0 五个辅助轴。",
    "六轴降抖": "越往右，辅助轴越不敏感、越平滑、越不容易抖。",
    "一键稳六轴": "把辅助轴调成低敏稳态，适合先解决抖动。",
    "六轴敏感度": "只调整非 L0 五个辅助轴；1 最稳，5 为新版默认，6-10 更灵敏。",
    "展开更多设置": "显示输入来源、声音、屏幕坐标和高级参数。",
    "收起更多设置": "隐藏不常用设置，让主界面更清爽。",
    "一键低敏六轴": "切到 Six Axis，并使用低敏但可见的辅助轴参数。",
    "反": "反转这个辅助轴的方向。",
    "L1": "前后 surge 辅助轴。",
    "L2": "左右 sway 辅助轴。",
    "R0": "twist 扭转轴。",
    "R1": "roll 横滚轴。",
    "R2": "pitch 俯仰轴。",
    "输入来源": "选择读取屏幕、读取视频文件或只监听声音。",
    "来源": "实时分析的数据来源。",
    "视频": "待分析的视频文件路径。",
    "选择": "选择本地视频文件。",
    "分析视频并保存脚本": "离线分析视频并导出 funscript。",
    "声音监听": "只根据声音强度或节拍输出 L0。",
    "声音分析": "选择音频转动作的方式。",
    "声音设备": "选择系统输出回环或麦克风输入。",
    "声音增益": "放大声音信号，越大越容易触发动作。",
    "声音门槛": "低于这个声音强度时不触发动作。",
    "声音平滑": "声音动作平滑程度，越高越稳但越慢。",
    "极端位自动复位": "卡在上限/下限附近太久时自动松回中段，防止一直顶住不动。",
    "极端停留 ms": "贴近上限/下限超过这个时间后才开始自动复位。",
    "端点保护": "实时输出时给上下极限留出缓冲，避免 L0 一直顶到机械端点。",
    "端点留白 %": "L0 上下两端保留多少行程；越大越不容易顶到底。",
    "屏幕区域": "限定读屏范围，减少无关画面干扰。",
    "X": "屏幕区域左上角横坐标。",
    "Y": "屏幕区域左上角纵坐标。",
    "宽": "读屏区域宽度。",
    "高": "读屏区域高度。",
    "框选区域": "用鼠标直观选择屏幕分析区域。",
    "高级参数": "控制分析、滤波、速度和响应方式。",
    "输出模式": "L0 Only 只输出上下；Six Axis 输出六轴。",
    "分析模式": "选择屏幕运动识别算法。",
    "Pose 倾向 L0": "根据姿态关键点分析运动，减少横向变化被误判为纵向变化。",
    "Pose 倾向六轴": "让横摆、扭腰、重复舞蹈更多体现在 L1/L2/R0/R1/R2 上。",
    "Pose L0 权重": "越大越偏向完整人物舞蹈/扭腰横摆理解，L0 越不容易把左右摆动误判成上下。",
    "Pose 六轴权重": "越大越像显示完整人物的舞蹈，横摆、扭腰和身体角度会更多分配给六轴辅助。",
    "基础分析 L0 权重": "显示 L0 基础分析方法还占多少。开启 Pose 倾向 L0 时等于 100 - Pose L0 权重；关闭时为 100%。",
    "基础分析六轴权重": "显示六轴基础分析方法还占多少。开启 Pose 倾向六轴时等于 100 - Pose 六轴权重；关闭时为 100%。",
    "Pose v2 舞蹈六轴测试": "测试版功能：在压缩延迟后的分析画面中拟合胯部平行四边形，用它的中心、角度、边长和面积辅助输出六轴。关闭后完全使用原逻辑。",
    "Pose v2 倾向 L0": "启用 Pose v2 对 L0 的辅助权重。开启 V2 时会自动关闭 V1 Pose 倾向。",
    "Pose v2 倾向六轴": "启用 Pose v2 对 L1/L2/R0/R1/R2 的辅助权重。开启 V2 时会自动关闭 V1 Pose 倾向。",
    "Pose v2 L0 权重": "越大越偏向 Pose v2 的胯部上下判断；建议先保持较低或关闭，保护原 L0 稳定手感。",
    "Pose v2 六轴权重": "越大越偏向 Pose v2 的胯部核心区、平行四边形和防卡边判断。",
    "基础分析 v2 L0 权重": "显示 L0 基础分析方法还占多少。开启 Pose v2 倾向 L0 时等于 100 - Pose v2 L0 权重；关闭时为 100%。",
    "基础分析 v2 六轴权重": "显示六轴基础分析方法还占多少。开启 Pose v2 倾向六轴时等于 100 - Pose v2 六轴权重；关闭时为 100%。",
    "RTM Pose 骨架标注": "测试版舞蹈模式：使用 RTM Pose 感知到的人体骨架做标注和输出。只在选择 RTM Pose 2D 舞蹈模式时启用。",
    "RTM Pose 模型": "选择本地 256x192 RTMPose 2D ONNX 模型；没有有效模型时不能开始 RTM 分析。",
    "基础分析 RTM 权重": "RTM Pose 是独立舞蹈模式，不接入混合分析权重。",
    "混合分析 L0 权重": "勾选后才会额外运行混合分析，只把它的 L0 按这个权重混入 RTM；不勾选时 RTM 保持 100% 模型并节省算力。",
    "当前本模型分析权重": "显示当前 RTM 模型在 L0 中占多少；未勾选混合分析时为 100%。",
    "RTM GPU 加速": "默认关闭。CUDA 适用于 NVIDIA，运行库较大；DirectML 支持 DirectX 12 的 AMD/NVIDIA/Intel，运行库较小。两者使用同一模型，准确度需同视频对比，不保证 CUDA 必然更准确。后台检测/安装，失败回退 CPU；安装或切换运行库需重启。",
    "RTM 光流辅助": "默认开启。用上一帧骨架关键点在新画面里做轻量追踪，补足两次模型检测之间的运动。",
    "RTM 卡尔曼融合": "默认开启。用光流作为预测，用 RTM 检测点作为观测进行融合，减少关键点跳动。",
    "反转": "反转这个输出方向；只改变最终轴方向，不改变识别算法。",
    "框选屏幕区域": "启动前重新选择实时读取范围，减少无关画面干扰。",
    "FPS": "每秒分析帧数，越高越跟手也越吃性能。",
    "间隔 ms": "TCode 命令的 I 时间，通常和输出刷新速度相关。",
    "到达时间下限 ms": "TCode 的最短到达时间。运行时还会参考实际更新间隔，接近上下限时可进一步延长；不是发送频率设置。",
    "启用每帧限速": "限制每帧最大变化，减少突然猛动。",
    "限速值": "每帧允许变化的最大 TCode 数值。",
    "启用平滑曲线": "对输出做平滑，减少生硬抖动。",
    "平滑": "越高越稳，越低越跟手。",
    "启用死区滤波": "忽略很小的画面变化。",
    "死区": "小于这个变化量时不更新输出。",
    "启用 L0 防抽搐": "专门压住 L0 小幅反复反转。",
    "L0 防抖": "越高 L0 越稳，但小动作会更钝。",
    "启用活动门控": "画面活动太小时保持当前动作或回中。",
    "活动阈值": "低于这个活动量时视为无有效运动。",
    "增益": "放大视觉运动，越大越敏感。",
    "视觉行程": "控制画面动作映射到 L0 行程的幅度。",
    "压缩延迟": "默认 0 不压缩画面。调到 1..5 会降低分析分辨率以减少延迟；-5..0 保持原始画面，优先准确。",
    "响应曲线": "改变中段和两端的响应手感。",
    "空闲": "无有效运动时保持当前位置或回中。",
    "启用启动渐入": "开始输出时逐渐进入动作，避免突然跳动。",
    "渐入 ms": "启动渐入持续时间。",
    "反向": "反转 L0 上下方向。",
    "一键稳态 L0": "把 L0 调成更稳、更少抽搐的参数。",
    "开始录制": "把实时输出记录为脚本。",
    "保存脚本": "保存当前录制的 funscript 文件。",
}

TOOLTIPS_EN = {
    "五档预设": "Set final script and live output travel to 0.55 / 0.75 / 1 / 1.15 / 1.30. Analysis mode, recognition settings and pose processing stay unchanged.",
    "仅调整最终输出幅度": "Applies to recording, exported scripts and live output. Raw analysis is unchanged; output limits and speed caps still apply.",
    "急停回中": "Stop realtime output immediately and move active axes back to center.",
    "全行程": "Use larger and faster L0 travel for full-range testing.",
    "连接并回中": "Connect the selected device and send a center command.",
    "连接中...": "Connecting in the background; the window stays usable if the port is bad.",
    "开始实时输出前确认": "Final check for output mode and limits before starting.",
    "L0 Only：只上下": "Only output the L0 vertical axis. Best for first tests.",
    "Six Axis：六轴": "Output L0/L1/L2/R0/R1/R2 together.",
    "确认开始": "Start realtime output with the selected settings.",
    "取消": "Close this dialog without starting output.",
    "连接设备": "Choose USB serial or BLE, then connect the SR6/OSR6 controller.",
    "输出": "Choose log-only, USB serial, or BLE UART output.",
    "串口": "USB or Bluetooth serial port, such as COMx.",
    "刷新": "Scan serial or audio devices again.",
    "波特率": "Serial speed. OSR devices commonly use 115200.",
    "自动检测 SR6/OSR6": "Pick the serial port that most likely belongs to SR6/OSR6.",
    "BLE 名称": "Filter BLE scan results by device name.",
    "扫描": "Scan nearby BLE UART devices.",
    "BLE 地址": "BLE device address, filled after scanning.",
    "写入 UUID": "BLE UART write characteristic UUID.",
    "断开": "Close the current device connection.",
    "查询设备轴": "Send D2 over serial to see which TCode axes the firmware exposes.",
    "实时输出": "Convert screen, video, or audio motion to realtime TCode output.",
    "下限": "Minimum allowed TCode value for this axis.",
    "上限": "Maximum allowed TCode value for this axis.",
    "速度": "Maximum TCode change per frame. Higher means faster motion.",
    "居中": "Send a center command.",
    "中等测试": "Send a small safe test motion.",
    "上下全幅测试": "Test the full L0 vertical range only.",
    "SR6/OSR6 六轴轻测": "Lightly test L0/L1/L2/R0/R1/R2 one by one.",
    "开始实时输出": "Start reading the selected input and controlling the device.",
    "恢复所有默认设置": "Restore factory defaults after a confirmation prompt.",
    "显示预览": "Open the 3D simulator for final output commands. Frames and skeletons are in Analysis Preview; the simulator is not hardware feedback.",
    "取消预览": "Stop preview sync. You can close the browser preview window.",
    "停止": "Stop realtime output while keeping the device connection.",
    "安全预设": "Slower and smaller motion, useful for first tests.",
    "标准预设": "Balanced daily settings.",
    "混合分析灵敏": "Use Hybrid Analysis with more direct response.",
    "六轴独立上下限": "Limit each physical axis separately.",
    "总行程倍率": "Scale all axis travel around center without crossing saved limits.",
    "L0 总行程倍率": "Scale only L0 travel without changing its mechanical limits.",
    "六轴总行程倍率": "Scale L1/L2/R0/R1/R2 travel without affecting L0.",
    "展开六轴单轴行程倍率": "Adjust L1/L2/R0/R1/R2 separately. Final travel = Six-Axis Travel Scale x per-axis scale.",
    "收起六轴单轴行程倍率": "Hide per-axis travel scales for L1/L2/R0/R1/R2.",
    "L1 行程倍率": "Per-axis travel scale for L1 surge, multiplied by the six-axis travel scale.",
    "L2 行程倍率": "Per-axis travel scale for L2 sway, multiplied by the six-axis travel scale.",
    "R0 行程倍率": "Per-axis travel scale for R0 twist, multiplied by the six-axis travel scale.",
    "R1 行程倍率": "Per-axis R1 roll scale, multiplied by six-axis travel. Direct Pose also contracts it with final L0: 1x from bottom through 2/3, then 0.5x at the top.",
    "R2 行程倍率": "Per-axis R2 pitch scale, multiplied by six-axis travel. Direct Pose also contracts it with final L0: 1x from bottom through 2/3, then 0.5x at the top.",
    "轴": "The TCode channel being viewed or adjusted.",
    "测量模式": "Manually control one axis with a slider and save safe limits.",
    "滑动即发送": "Send commands immediately while dragging the measurement slider.",
    "位置": "Current manual TCode position.",
    "发送当前位置": "Send the measurement slider value to the selected axis.",
    "保存为下限": "Save the current measurement value as this axis lower limit.",
    "当前轴回中": "Move the selected measurement axis to 5000.",
    "保存为上限": "Save the current measurement value as this axis upper limit.",
    "六轴辅助调节（仅混合分析推荐）": "Tune L1/L2/R0/R1/R2 for Hybrid Analysis only. RTM Pose does not use these controls.",
    "展开测量模式和轴上下限": "Show measurement mode and per-axis safety limits.",
    "收起测量模式和轴上下限": "Hide measurement mode and per-axis safety limits.",
    "展开六轴辅助调节（仅混合分析）": "Show six-axis helper tuning for Hybrid Analysis.",
    "收起六轴辅助调节（仅混合分析）": "Hide six-axis helper tuning for Hybrid Analysis.",
    "展开 RTM Pose 模型设置": "Show RTM Pose model path, download, and source details. Only visible in RTM Pose 2D dance modes.",
    "收起 RTM Pose 模型设置": "Hide RTM Pose model settings to keep the main controls cleaner.",
    "总强度": "Overall strength for the five non-L0 auxiliary axes.",
    "六轴降抖": "Higher values make auxiliary axes less sensitive, smoother, and steadier.",
    "一键稳六轴": "Apply a low-sensitivity six-axis setup to reduce jitter.",
    "六轴敏感度": "Adjust non-L0 axes only. 1 is steadiest, 5 is default, 6-10 are more sensitive.",
    "展开更多设置": "Show input, audio, screen region, and advanced settings.",
    "收起更多设置": "Hide less common settings for a cleaner main view.",
    "一键低敏六轴": "Switch to Six Axis with visible but low-sensitivity auxiliary motion.",
    "反": "Invert this auxiliary axis direction.",
    "L1": "Surge auxiliary axis.",
    "L2": "Sway auxiliary axis.",
    "R0": "Twist axis.",
    "R1": "Roll axis.",
    "R2": "Pitch axis.",
    "输入来源": "Choose screen capture, video file, or audio-only listening.",
    "来源": "The data source for realtime analysis.",
    "视频": "Path to the video file to analyze.",
    "选择": "Choose a local video file.",
    "分析视频并保存脚本": "Analyze a video offline and export funscript files.",
    "声音监听": "Output L0 from audio level or rhythm only.",
    "声音分析": "Choose how audio is converted to motion.",
    "声音设备": "Choose system loopback or microphone input.",
    "声音增益": "Boost the audio signal. Higher values trigger motion more easily.",
    "声音门槛": "Audio below this level will not trigger motion.",
    "声音平滑": "Higher values are steadier but respond slower.",
    "极端位自动复位": "If the output stays near an endpoint too long, ease back toward center.",
    "极端停留 ms": "How long the output must stay near an endpoint before auto reset starts.",
    "端点保护": "Leave buffer near mechanical extremes during realtime output.",
    "端点留白 %": "How much L0 travel to reserve at both ends.",
    "屏幕区域": "Limit the screen-reading area to reduce unrelated motion.",
    "X": "Left coordinate of the screen region.",
    "Y": "Top coordinate of the screen region.",
    "宽": "Width of the screen-reading region.",
    "高": "Height of the screen-reading region.",
    "框选区域": "Select the screen analysis region with the mouse.",
    "高级参数": "Control analysis, filtering, speed, and response.",
    "输出模式": "L0 Only controls vertical motion only. Six Axis controls all axes.",
    "分析模式": "Choose the screen motion analysis method.",
    "Pose 倾向 L0": "Useful for dance or full-body motion; prevents L0 from overreacting to side-to-side motion.",
    "Pose 倾向六轴": "Map sway, twist, and body angle more strongly to auxiliary axes.",
    "Pose L0 权重": "Higher values favor full-body dance interpretation and reduce false L0 extremes.",
    "Pose 六轴权重": "Higher values make full-body dance, sway, and angle drive auxiliary axes more.",
    "基础分析 L0 权重": "Shows how much the original L0 analysis still contributes. With Pose L0 enabled, it is 100 minus Pose L0 weight; when disabled, it is 100%.",
    "基础分析六轴权重": "Shows how much the original six-axis analysis still contributes. With Pose Six-Axis enabled, it is 100 minus Pose Six-Axis weight; when disabled, it is 100%.",
    "Pose v2 舞蹈六轴测试": "Test feature: fits a hip-plane parallelogram on the frame after Compression / Latency, then uses its center, angle, edge length, and area to assist six-axis output. Turn it off to use the original logic.",
    "Pose v2 倾向 L0": "Enable Pose v2 assist for L0. Turning on V2 automatically turns off V1 Pose bias.",
    "Pose v2 倾向六轴": "Enable Pose v2 assist for L1/L2/R0/R1/R2. Turning on V2 automatically turns off V1 Pose bias.",
    "Pose v2 L0 权重": "Higher values favor Pose v2 hip vertical tracking. Start low or leave it off to preserve stable L0 behavior.",
    "Pose v2 六轴权重": "Higher values favor Pose v2 hip-core, parallelogram, and anti-stuck side-axis tracking.",
    "基础分析 v2 L0 权重": "Shows how much the original L0 analysis still contributes. With Pose v2 L0 enabled, it is 100 minus Pose v2 L0 weight; when disabled, it is 100%.",
    "基础分析 v2 六轴权重": "Shows how much the original six-axis analysis still contributes. With Pose v2 Six-Axis enabled, it is 100 minus Pose v2 Six-Axis weight; when disabled, it is 100%.",
    "RTM Pose 骨架标注": "Test dance mode: uses the skeleton perceived by RTM Pose for overlay and output. Only active in RTM Pose 2D dance modes.",
    "RTM Pose 模型": "Select a local 256x192 RTMPose 2D ONNX model. RTM analysis requires a valid model.",
    "基础分析 RTM 权重": "RTM Pose is a separate dance mode and does not use Hybrid Analysis weighting.",
    "混合分析 L0 权重": "When checked, Hybrid Analysis runs only for L0 and is mixed into RTM by this weight. When unchecked, RTM stays 100% model-driven and saves CPU.",
    "当前本模型分析权重": "Shows how much RTM model analysis currently contributes to L0. It is 100% when Hybrid L0 is unchecked.",
    "RTM GPU 加速": "Off by default. CUDA (NVIDIA) has larger runtime libraries; DirectML (DirectX 12 AMD/NVIDIA/Intel) has smaller ones. Both use the same model; compare the same video before claiming an accuracy advantage. Background checks/install; CPU fallback on failure. Restart after runtime installation or switching.",
    "RTM 光流辅助": "On by default. Tracks the previous skeleton keypoints in the next frame to fill motion between model detections.",
    "RTM 卡尔曼融合": "On by default. Uses optical flow as prediction and RTM detections as observations to reduce keypoint jitter.",
    "反转": "Invert this output direction. It changes the final axis direction only, not the recognition algorithm.",
    "框选屏幕区域": "Select the realtime capture region before starting.",
    "FPS": "Frames analyzed per second. Higher is more responsive and uses more CPU.",
    "间隔 ms": "The TCode I time, usually related to output refresh speed.",
    "到达时间下限 ms": "Minimum TCode arrival time. Actual update cadence and endpoint slowdown can extend it; this does not set the send frequency.",
    "启用每帧限速": "Limit maximum change per frame to reduce sudden moves.",
    "限速值": "Maximum TCode change allowed per frame.",
    "启用平滑曲线": "Smooth the output to reduce harsh jitter.",
    "平滑": "Higher is steadier. Lower follows the picture more directly.",
    "启用死区滤波": "Ignore very small screen changes.",
    "死区": "Ignore updates smaller than this amount.",
    "启用 L0 防抽搐": "Specifically reduce tiny rapid L0 reversals.",
    "L0 防抖": "Higher makes L0 steadier, but small motion becomes softer.",
    "启用活动门控": "When screen activity is too low, hold or center instead of chasing noise.",
    "活动阈值": "Activity below this value is treated as no useful motion.",
    "增益": "Amplify visual motion sensitivity.",
    "视觉行程": "How much visual motion maps to L0 travel.",
    "压缩延迟": "Default 0 keeps the original frame. 1..5 lowers analysis resolution for less latency; -5..0 keeps original detail for accuracy.",
    "响应曲线": "Change response feel around center and endpoints.",
    "空闲": "What to do when there is no useful motion.",
    "启用启动渐入": "Ramp in at start to avoid a sudden jump.",
    "渐入 ms": "Duration of startup ramp.",
    "反向": "Invert L0 vertical direction.",
    "一键稳态 L0": "Set L0 to a steadier, less jittery setup.",
    "开始录制": "Record realtime output as a script.",
    "保存脚本": "Save the current recording as funscript files.",
}


class Tooltip:
    def __init__(self, widget: tk.Widget, text: str) -> None:
        self.widget = widget
        self.text = text
        self.window: tk.Toplevel | None = None
        self.after_id: str | None = None
        widget.bind("<Enter>", self._schedule, add="+")
        widget.bind("<Leave>", self._hide, add="+")
        widget.bind("<ButtonPress>", self._hide, add="+")

    def _schedule(self, _event: tk.Event | None = None) -> None:
        self._cancel()
        self.after_id = self.widget.after(420, self._show)

    def _show(self) -> None:
        if self.window is not None:
            return
        x, y = (physical_cursor_position() if sys.platform.startswith("win") else
                (self.widget.winfo_pointerx(), self.widget.winfo_pointery()))
        x, y = x + 14, y + 14
        self.window = tk.Toplevel(self.widget)
        self.window.wm_overrideredirect(True)
        label = tk.Label(
            self.window,
            text=self.text,
            justify="left",
            background="#222831",
            foreground="#f7f7f7",
            relief="solid",
            borderwidth=1,
            padx=8,
            pady=5,
            wraplength=260,
        )
        label.pack()
        self.window.update_idletasks()
        width, height = self.window.winfo_reqwidth(), self.window.winfo_reqheight()
        left, top, right, bottom = monitor_workarea(self.widget)
        place_physical_window(self.window, dict(left=max(left, min(x, right-width)),
            top=max(top, min(y, bottom-height)), width=width, height=height))

    def _hide(self, _event: tk.Event | None = None) -> None:
        self._cancel()
        if self.window is not None:
            self.window.destroy()
            self.window = None

    def _cancel(self) -> None:
        if self.after_id is not None:
            try:
                self.widget.after_cancel(self.after_id)
            except tk.TclError:
                pass
            self.after_id = None
